Updating with new Phis tests
H2020-IPM-openalea/agroservices pull request #19
Opened 2024-01-22 15:51 UTC by AurelienBesnier

2024-01-23 16:30 UTC, pradal approved these changes

2024-01-29 19:18 UTC, pradal commented
Warning : we need to modify all the packages that depend on agroservice if we change its import!
@christian34

2025-02-14 13:51 UTC, pradal requested changes
That's a great contribution. Thanks.
Few comments to consider before I merge.

2025-02-14 13:51 UTC, pradal commented on conda/meta.yaml
> +  version: "1.0.1"
Add it in pyproject.toml as dynamic in a file inside the source

2025-02-14 13:51 UTC, pradal commented on doc/environment.yml
> + - myst-parser
Add a blank line at the end of the file

2025-02-14 13:51 UTC, pradal commented on pyproject.toml
> +  { name = "Marc Labadie"},
Add yourself as author!

2025-02-14 13:51 UTC, pradal commented on pyproject.toml
> +Homepage = "https://github.com/openalea/agroservices"
Perhaps add the readthedoc as homepage?

2025-02-14 13:51 UTC, pradal commented on src/openalea/agroservices/extern/easydev/tools.py
>  class DevTools(object):
remove object inheritance

2025-02-14 15:04 UTC, AurelienBesnier commented on conda/meta.yaml
> +  version: "1.0.1"
The version is dynamic in the pyproject.toml. 
I tried to set it in the meta.yaml with `{% set pyproject = load_file_data('pyproject.toml') %}` but the version returned by this is always `None`.

2025-02-14 16:32 UTC, pradal commented on README.md
> +
I will not recommend to install openalea with venv unless we are able to install everything with venv.
We can limit us to mamba

2025-02-14 16:32 UTC, pradal commented on README.md
>  conda activate agroservices
It will be better to create an environment.yml

2025-02-14 16:32 UTC, pradal commented on README.md
>  conda activate agroservices
And use mamba instead...

2025-02-14 17:47 UTC, pradal approved these changes

2025-02-14 17:47 UTC, merged